import { ArchitecturalElementCategory } from '../types';

export const ARCHITECTURAL_ELEMENTS: ArchitecturalElementCategory[] = [
  {
    category: 'Kết cấu & Mái',
    options: [
      { id: 'ext-struct-nharuong', name: 'Kết cấu Nhà Rường', prompt: 'a traditional Vietnamese "Nhà Rường" wooden structure with exposed columns, beams, and trusses', description: 'Hệ kết cấu cột-kèo-xuyên-trụ bằng gỗ đặc trưng.' },
      { id: 'ext-roof-amduong', name: 'Mái ngói Âm Dương', prompt: 'a traditional yin-yang tiled roof with decorative ridge and hip details', description: 'Loại ngói ống lợp một úp một ngửa quen thuộc.' },
      { id: 'ext-roof-muihai', name: 'Mái ngói Mũi Hài', prompt: 'an ancient-style "hài" (shoe) shaped tile roof', description: 'Loại ngói có hình dáng như chiếc hài cổ, lợp vảy cá.' },
      { id: 'ext-roof-sweeping', name: 'Mái cong vút', prompt: 'a majestic, sweeping roof with gracefully curved eaves, typical of temples and communal houses', description: 'Dáng mái có độ cong ở các góc, tạo sự thanh thoát.' },
      { id: 'ext-roof-thainhat', name: 'Mái Nhật/Thái', prompt: 'a modern pitched roof inspired by Japanese or Thai architecture, with clean lines and wide eaves', description: 'Hệ mái dốc hiện đại, lợp ngói phẳng hoặc ngói sóng.' },
      { id: 'ext-struct-veranda', name: 'Hàng hiên rộng', prompt: 'a deep, shaded veranda supported by wooden or masonry columns', description: 'Không gian chuyển tiếp trước nhà, che nắng che mưa.' },
      { id: 'ext-roof-4-slope', name: 'Mái 4 mái', prompt: 'a traditional four-slope hipped roof (mái bốn mái) with equal slopes on all sides, common in Vietnamese vernacular architecture', description: 'Mái 4 đổ dốc đều đặn, kiến trúc dân gian phổ biến.' },
      { id: 'ext-roof-2-slope', name: 'Mái 2 mái đơn giản', prompt: 'a simple two-slope gable roof (mái hai mái) with triangular gable ends, economical and practical', description: 'Mái 2 dốc hình chữ A đơn giản, tiết kiệm, thực dụng.' },
      { id: 'ext-roof-multi-tier', name: 'Mái nhiều tầng chồng', prompt: 'a multi-tiered roof structure with stacked layers, creating impressive height and ceremonial appearance typical of pagodas and temples', description: 'Hệ mái nhiều tầng xếp chồng, tạo uy nghi trang trọng.' },
      { id: 'ext-roof-rau-qua', name: 'Mái Rạu Quạ', prompt: 'a traditional thatched roof with dried grass or palm leaves, rustic rural architecture', description: 'Mái lợp rơm/lá cọ truyền thống, mộc mạc làng quê.' },
      { id: 'ext-roof-flat-modern', name: 'Mái bằng hiện đại', prompt: 'a modern flat roof with waterproof membrane and green roof possibility, contemporary sustainable design', description: 'Mái phẳng hiện đại, có thể làm vườn trên mái.' },
      { id: 'ext-struct-pavilion', name: 'Kết cấu Đình (Pavilion)', prompt: 'an open pavilion structure with tall columns supporting an ornate roof, no walls on sides for ventilation', description: 'Kết cấu nhà đình không tường, cột cao, thoáng mát.' },
      { id: 'ext-struct-wood-frame', name: 'Khung gỗ lộ thiên', prompt: 'exposed wooden frame structure with visible joinery and craftsmanship, showcasing traditional carpentry techniques', description: 'Khung gỗ để lộ ra ngoài, thể hiện kỹ thuật mộc.' },
      { id: 'ext-struct-brick-bearing', name: 'Tường gạch chịu lực', prompt: 'traditional load-bearing brick walls with thick masonry, typical of French colonial influenced architecture', description: 'Tường gạch dày chịu lực, ảnh hưởng Pháp thuộc.' },
      { id: 'ext-roof-barrel-vault', name: 'Vòm thùng', prompt: 'a barrel vault roof structure creating spacious interior, inspired by European and Chinese architectural fusion', description: 'Mái vòm thùng tạo không gian rộng, ảnh hưởng Âu-Hoa.' },
    ],
  },
  {
    category: 'Cửa & Chi tiết mặt tiền',
    options: [
      { id: 'ext-door-bucban', name: 'Cửa Bức Bàn', prompt: 'traditional "cửa bức bàn" - a system of removable wooden wall panels that act as doors', description: 'Hệ cửa gỗ nhiều cánh có thể tháo rời, linh hoạt.' },
      { id: 'ext-window-thuongxong', name: 'Cửa sổ Thượng song hạ bản', prompt: 'a classic window style with an upper wooden lattice (song) and a solid lower panel (bản)', description: 'Trên là chấn song, dưới là pano gỗ đặc.' },
      { id: 'ext-window-batsat', name: 'Cửa sổ Bát giác', prompt: 'an octagonal window, often with wooden louvers or intricate carvings', description: 'Cửa sổ hình 8 cạnh, một chi tiết đặc trưng.' },
      { id: 'ext-facade-louvers', name: 'Lam gỗ chắn nắng', prompt: 'a facade with vertical or horizontal wooden louvers (brise-soleil) for sun shading', description: 'Hệ lam bằng gỗ che nắng cho mặt tiền.' },
      { id: 'ext-facade-gachbonggio', name: 'Tường gạch bông gió', prompt: 'a decorative and functional facade made of terracotta or cement breeze blocks', description: 'Mảng tường xây bằng gạch thông gió, tạo hoa văn và đối lưu không khí.' },
      { id: 'ext-facade-facade-green', name: 'Mặt đứng xanh', prompt: 'a green facade with integrated planters and climbing vegetation', description: 'Mặt tiền được bao phủ bởi cây xanh, dây leo.' },
      { id: 'ext-door-double-leaf', name: 'Cửa 2 cánh gỗ lớn', prompt: 'grand double-leaf wooden doors with carved decorative panels, brass hardware, and traditional door gods (thần tài) motifs', description: 'Cửa đôi gỗ lớn chạm khắc, có họa tiết thần tài.' },
      { id: 'ext-door-arched', name: 'Cửa vòm cong', prompt: 'arched doorway with semicircular or pointed arch, influenced by French colonial and religious architecture', description: 'Cửa có vòm cong, ảnh hưởng kiến trúc Pháp và nhà thờ.' },
      { id: 'ext-window-round', name: 'Cửa sổ tròn (Giếng trời mini)', prompt: 'circular windows or moon gate openings providing ventilation and decorative focal points', description: 'Cửa sổ hình tròn kiểu giếng trời nhỏ, trang trí.' },
      { id: 'ext-window-shutters', name: 'Cửa sổ Chớp màu xanh', prompt: 'wooden shutters painted in traditional green or blue colors, typical of French colonial shophouses', description: 'Cửa chớp gỗ sơn xanh lá/xanh dương, kiểu nhà Pháp.' },
      { id: 'ext-window-floor-to-ceiling', name: 'Cửa kính từ sàn đến trần', prompt: 'modern floor-to-ceiling glass windows providing maximum natural light and connection to exterior', description: 'Cửa kính lớn hiện đại, tối đa ánh sáng tự nhiên.' },
      { id: 'ext-facade-perforated', name: 'Vách đục lỗ nghệ thuật', prompt: 'perforated facade panels with artistic patterns allowing light and air penetration while maintaining privacy', description: 'Vách đục lỗ họa tiết, vừa thoáng vừa riêng tư.' },
      { id: 'ext-facade-double-skin', name: 'Mặt tiền da kép', prompt: 'double-skin facade system with an outer sun-shading layer and inner glazing for climate control', description: 'Hệ mặt tiền 2 lớp che nắng, điều hòa khí hậu.' },
      { id: 'ext-window-bay', name: 'Cửa sổ Lồi (Bay window)', prompt: 'protruding bay windows creating extra interior space and panoramic views', description: 'Cửa sổ nhô ra ngoài, mở rộng không gian và tầm nhìn.' },
      { id: 'ext-door-pivot', name: 'Cửa Trục xoay hiện đại', prompt: 'modern pivot door with central or offset axis, creating dramatic entrance statement', description: 'Cửa trục xoay hiện đại, lối vào ấn tượng.' },
      { id: 'ext-facade-ceramic', name: 'Mặt tiền Gốm sứ', prompt: 'facade clad with ceramic tiles in traditional or contemporary patterns, weather-resistant and colorful', description: 'Mặt tiền ốp gốm sứ, họa tiết, chống nước, màu sắc.' },
      { id: 'ext-window-clerestory', name: 'Cửa sổ Cao (Clerestory)', prompt: 'high clerestory windows near the roof line for natural lighting without compromising privacy', description: 'Cửa sổ cao gần mái, lấy sáng không mất riêng tư.' },
    ],
  },
  {
    category: 'Cảnh quan & Sân vườn',
    options: [
        { id: 'ext-garden-thientinh', name: 'Sân Thiên Tỉnh (giếng trời)', prompt: 'an internal courtyard open to the sky ("thiên tỉnh"), often with a small garden or water feature', description: 'Khoảng sân trong nhà, giúp lấy sáng và thông gió.' },
        { id: 'ext-garden-binhphong', name: 'Bình phong chắn', prompt: 'a decorative screen (bình phong), either masonry or masonry with mosaic, placed in front of the main entrance', description: 'Tấm bình phong xây trước cửa chính để chắn tà khí.' },
        { id: 'ext-garden-honnonbo', name: 'Hòn non bộ & Hồ nước', prompt: 'a miniature rock mountain landscape (hòn non bộ) set within a small pond or water feature', description: 'Tiểu cảnh núi đá và hồ nước theo triết lý phong thủy.' },
        { id: 'ext-garden-daongoi', name: 'Lối đi dạo lát đá/gạch', prompt: 'a meandering garden path paved with natural stone slabs or old bricks', description: 'Đường đi trong vườn lát bằng đá tự nhiên hoặc gạch cổ.' },
        { id: 'ext-garden-gienglang', name: 'Giếng nước', prompt: 'a traditional village water well with a masonry surround', description: 'Giếng làng xây bằng gạch hoặc đá, nơi sinh hoạt chung.' },
        { id: 'ext-garden-luytre', name: 'Lũy tre xanh', prompt: 'a dense hedge or grove of bamboo surrounding the property', description: 'Hàng rào tự nhiên bằng tre, đặc trưng của làng quê.' },
        { id: 'ext-tree-co-thu', name: 'Cây cổ thụ (đa, bồ đề)', prompt: 'a large, ancient tree like a banyan or bodhi tree providing shade', description: 'Một cây lớn có tuổi đời lâu năm, tỏa bóng mát.' },
        { id: 'ext-tree-cau', name: 'Hàng cau', prompt: 'a row of tall, slender areca palm trees', description: 'Hàng cây cau thẳng tắp, một hình ảnh quen thuộc.' },
        { id: 'ext-garden-zen', name: 'Vườn Thiền Nhật Bản', prompt: 'a minimalist Zen garden with raked gravel, carefully placed rocks, and pruned trees', description: 'Vườn thiền tối giản với sỏi, đá, cây tỉa.' },
        { id: 'ext-garden-herb', name: 'Vườn rau thảo mộc', prompt: 'a traditional herb and vegetable garden with raised beds, bamboo trellises, and medicinal plants', description: 'Vườn rau thảo dược với luống cao, giàn tre.' },
        { id: 'ext-water-lotus-pond', name: 'Ao sen', prompt: 'a lotus pond with blooming lotus flowers, lily pads, and stone edges, symbol of purity in Vietnamese culture', description: 'Ao sen nở hoa, biểu tượng thanh tịnh Phật giáo.' },
        { id: 'ext-water-koi-pond', name: 'Hồ cá Koi', prompt: 'a decorative koi fish pond with clear water, aquatic plants, and viewing stones', description: 'Hồ cá Koi cảnh, nước trong, thủy sinh, đá cảnh.' },
        { id: 'ext-water-stream', name: 'Suối nhỏ nhân tạo', prompt: 'an artificial stream with flowing water, natural stones, and lush vegetation creating tranquil ambiance', description: 'Suối nhỏ nước chảy, đá tự nhiên, cây xanh mát.' },
        { id: 'ext-garden-bonsai', name: 'Vườn Cây cảnh & Bonsai', prompt: 'a display garden featuring traditional Vietnamese bonsai trees (cây cảnh) in ceramic pots on stone pedestals', description: 'Vườn trưng bày cây cảnh bonsai trong chậu gốm.' },
        { id: 'ext-garden-flower', name: 'Vườn hoa nhiệt đới', prompt: 'a tropical flower garden with vibrant orchids, hibiscus, frangipani, and native flowering plants', description: 'Vườn hoa nhiệt đới: lan, dâm bụt, hoa sứ...' },
        { id: 'ext-structure-gazebo', name: 'Chòi nghỉ/Đình vườn', prompt: 'a traditional garden pavilion or gazebo (chòi) with thatched or tiled roof for rest and contemplation', description: 'Chòi nghỉ mái rạ/ngói trong vườn để ngồi thư giãn.' },
        { id: 'ext-structure-bridge', name: 'Cầu nhỏ qua ao', prompt: 'a small arched wooden or stone bridge crossing a pond or stream, creating scenic focal point', description: 'Cầu gỗ/đá nhỏ bắc qua ao suối, điểm nhấn cảnh quan.' },
        { id: 'ext-garden-vertical', name: 'Vườn đứng (Vertical Garden)', prompt: 'a vertical garden system with climbing plants and wall-mounted planters, modern green solution', description: 'Vườn tường đứng với cây leo, giải pháp xanh hiện đại.' },
        { id: 'ext-garden-rice-paddy', name: 'Ruộng lúa cảnh quan', prompt: 'terraced rice paddies integrated into landscape design, celebrating agricultural heritage', description: 'Ruộng bậc thang lúa trong thiết kế, tôn vinh nông nghiệp.' },
        { id: 'ext-garden-tea', name: 'Vườn trà', prompt: 'a traditional tea garden with camellia sinensis plants, stone paths, and outdoor tea ceremony space', description: 'Vườn trồng chè với lối đi đá, không gian trà đạo.' },
        { id: 'ext-lighting-lantern', name: 'Đèn lồng sân vườn', prompt: 'traditional stone or metal lanterns illuminating garden paths, creating warm evening ambiance', description: 'Đèn lồng đá/kim loại chiếu sáng đường đi, ấm áp.' },
    ],
  },
  {
    category: 'Yếu tố Trang trí Đặc trưng',
    options: [
        { id: 'ext-decor-daohoi', name: 'Trang trí Đầu hồi', prompt: 'ornate decorations on the gable ends (đầu hồi) of the roof', description: 'Họa tiết, điêu khắc ở hai đầu hồi mái nhà.' },
        { id: 'ext-decor-bonoc', name: 'Trang trí Bờ nóc', prompt: 'decorative elements along the roof ridge (bờ nóc), often featuring dragons, phoenixes, or mosaic work', description: 'Họa tiết trang trí chạy dọc trên đỉnh mái.' },
        { id: 'ext-decor-khamsanhsu', name: 'Chi tiết khảm sành sứ', prompt: 'intricate mosaic details made from broken porcelain and ceramic pieces on walls, columns, or screens', description: 'Nghệ thuật dùng mảnh gốm sứ vỡ để trang trí.' },
        { id: 'ext-decor-phaplam', name: 'Chi tiết Pháp Lam', prompt: 'the inclusion of colorful Hue-style cloisonné enamel (Pháp Lam) on architectural elements', description: 'Các chi tiết bằng đồng tráng men màu, đặc trưng của Huế.' },
        { id: 'ext-decor-phudieu', name: 'Phù điêu đắp nổi', prompt: 'bas-relief sculptures or decorative plasterwork on the facade', description: 'Các hình trang trí được đắp nổi bằng vữa trên tường.' },
        { id: 'ext-decor-rong-chau', name: 'Rồng chầu mặt trăng/ngọc', prompt: 'traditional dragon motif chasing the moon or pearl decoration on roof ridges and gables, symbolizing prosperity', description: 'Họa tiết rồng chầu trên mái và đầu hồi, biểu tượng thịnh vượng.' },
        { id: 'ext-decor-long-ma', name: 'Tứ Linh (Long, Ly, Quy, Phượng)', prompt: 'decorative sculptures of the Four Sacred Animals - Dragon, Unicorn, Tortoise, Phoenix on architectural elements', description: 'Tứ linh trang trí trên cột, tường, mái - biểu tượng quyền lực và linh thiêng.' },
        { id: 'ext-decor-hoa-van-cham', name: 'Hoa văn Chăm Pa', prompt: 'intricate Champa-style relief patterns featuring geometric designs, floral motifs, and religious symbols on brick or stone surfaces', description: 'Họa tiết phù điêu Chăm với hình học, hoa văn và biểu tượng tôn giáo.' },
        { id: 'ext-decor-cau-doi', name: 'Hoành phi & Câu đối', prompt: 'horizontal lacquered boards (hoành phi) and parallel sentences (câu đối) with gold calligraphy at entrance gates', description: 'Bảng hoành phi và câu đối sơn son thếp vàng ở cổng vào.' },
        { id: 'ext-decor-con-rai', name: 'Con Rái (đầu rồng nước)', prompt: 'decorative water spouts shaped like Makara (con rái) - mythical sea creatures at roof corners for water drainage', description: 'Đầu rồng nước ở góc mái, vừa thoát nước vừa trang trí.' },
        { id: 'ext-decor-qua-cau', name: 'Trái cầu đá/Đá Nghê', prompt: 'stone spheres (trái cầu) or stone mythical lion-dogs (đá nghê) as guardian statues at entrances', description: 'Trái cầu đá hoặc nghê đá gác cổng bảo vệ công trình.' },
        { id: 'ext-decor-hoa-sen', name: 'Hoa văn Hoa Sen', prompt: 'lotus flower motifs carved or painted on columns, beams, and decorative panels, Buddhist symbolism', description: 'Họa tiết hoa sen chạm/vẽ trên cột, kèo, biểu tượng Phật giáo.' },
        { id: 'ext-decor-song-long', name: 'Song Long chầu Nguyệt', prompt: 'twin dragons chasing the moon motif on roof ridges, imperial symbolism', description: 'Đôi rồng chầu trăng trên bờ nóc, biểu tượng hoàng gia.' },
        { id: 'ext-decor-bat-tien', name: 'Bát Tiên (Tám Vị Tiên)', prompt: 'the Eight Immortals figures carved or depicted in decorative panels, Taoist mythology', description: 'Tám vị tiên chạm khắc hoặc vẽ, thần thoại Đạo giáo.' },
        { id: 'ext-decor-hoa-cuon-thao', name: 'Hoa văn Cuốn thảo', prompt: 'scrolling vine and foliage patterns (cuốn thảo) on columns, beams, and door frames', description: 'Họa tiết dây leo cuộn trên cột, kèo, khung cửa.' },
        { id: 'ext-decor-mat-troi', name: 'Biểu tượng Mặt trời', prompt: 'sun disc motifs symbolizing light, life, and prosperity in traditional architecture', description: 'Mặt trời trang trí, biểu tượng ánh sáng, sinh khí.' },
        { id: 'ext-decor-van-tu-phuc', name: 'Chữ Vạn (卍 - Phúc)', prompt: 'swastika symbol (vạn tự) representing eternity and good fortune in Buddhist and Hindu traditions', description: 'Chữ Vạn biểu tượng vĩnh cửu, may mắn Phật giáo.' },
        { id: 'ext-decor-chim-phung', name: 'Chim Phượng Hoàng', prompt: 'phoenix bird carvings representing grace, virtue, and feminine energy', description: 'Chim phượng chạm khắc, biểu tượng ân đức, nữ tính.' },
        { id: 'ext-decor-rua-thanh', name: 'Rùa Thần (Huyền Vũ)', prompt: 'sacred tortoise carvings symbolizing longevity, stability, and protection', description: 'Rùa thần chạm khắc, biểu tượng trường thọ, bảo vệ.' },
        { id: 'ext-decor-doi-doi', name: 'Dơi (Phúc)', prompt: 'bat motifs representing happiness and good fortune (dơi = phúc in Vietnamese)', description: 'Họa tiết con dơi, biểu tượng phúc lộc may mắn.' },
        { id: 'ext-decor-cuc-tho', name: 'Cúc & Đào (Hoa tứ quý)', prompt: 'chrysanthemum and peach blossom motifs from the Four Noble Flowers symbolizing seasons', description: 'Hoa cúc và đào từ Tứ quý, biểu tượng bốn mùa.' },
        { id: 'ext-decor-chum-nen', name: 'Chum nến/Trái Bầu', prompt: 'decorative candle holders or gourd-shaped finials on roof ridges and pavilions', description: 'Chum nến hoặc trái bầu trang trí trên mái, đình.' },
        { id: 'ext-decor-gia-dung', name: 'Hình ảnh Gia đình & Cộng đồng', prompt: 'relief carvings depicting daily life, family scenes, and community activities', description: 'Phù điêu sinh hoạt hàng ngày, gia đình, cộng đồng.' },
        { id: 'ext-decor-tho-cong', name: 'Dụng cụ Thợ thủ công', prompt: 'decorative elements featuring traditional craft tools (carpentry, weaving, fishing)', description: 'Trang trí công cụ nghề thủ công truyền thống.' },
    ],
  },
  {
    category: 'Yếu tố Văn hóa Miền Trung',
    options: [
        { id: 'ext-culture-cua-tam-quan', name: 'Cổng Tam Quan', prompt: 'traditional three-entrance gate (Tam Quan) with central main gate and two side gates, typical of temples and communal houses', description: 'Cổng ba lối vào đặc trưng của đình, chùa, nhà thờ họ.' },
        { id: 'ext-culture-chuong-trong', name: 'Chuông & Trống', prompt: 'bell and drum towers (Chuông Trống) flanking the main temple entrance, symbolic religious architecture', description: 'Chuông trống gác cổng chùa, biểu tượng kiến trúc tôn giáo.' },
        { id: 'ext-culture-tuong-phat', name: 'Tượng Phật Quan Âm', prompt: 'large statue of Buddha or Quan Am (Avalokitesvara) as focal point in temple courtyard or garden', description: 'Tượng Phật hoặc Quan Âm lớn trong sân chùa hoặc vườn.' },
        { id: 'ext-culture-thap-huong', name: 'Tháp Hương', prompt: 'incense tower (Tháp Hương) with multiple tiers for burning incense, common in Central Vietnamese temples', description: 'Tháp nhiều tầng để đốt hương, phổ biến ở chùa miền Trung.' },
        { id: 'ext-culture-cau-ngoi', name: 'Cầu Ngói cổ', prompt: 'ancient tile-roofed bridge with traditional Vietnamese architectural style, connecting village areas across streams', description: 'Cầu lợp ngói kiến trúc truyền thống nối các khu vực làng qua suối.' },
        { id: 'ext-culture-nha-tro', name: 'Nhà Trọ Trạm', prompt: 'traditional wayside rest house (Nhà trọ) with open shelter, seating area, water supply for travelers', description: 'Nhà nghỉ ven đường với mái che, chỗ ngồi, nước uống cho khách qua lại.' },
        { id: 'ext-culture-bia-da', name: 'Bia đá ký sự', prompt: 'stone stele with inscribed historical records, genealogy, or village regulations, mounted on tortoise base', description: 'Bia đá khắc lịch sử, gia phả hoặc hương ước làng, đặt trên lưng rùa đá.' },
        { id: 'ext-culture-lang-mo', name: 'Lăng mộ Miền Trung', prompt: 'traditional Central Vietnamese tomb architecture with horseshoe-shaped grave mound, stone guardian statues, and ancestor altar', description: 'Mộ phần hình móng ngựa, tượng đá gác mộ, bàn thờ tiền nhân kiểu miền Trung.' },
        { id: 'ext-culture-cot-co', name: 'Cột cờ Đình làng', prompt: 'tall flagpole (Cột cờ) structure in communal house courtyard, symbol of village authority and gathering point', description: 'Cột cờ cao trong sân đình, biểu tượng quyền lực làng và điểm tụ họp.' },
        { id: 'ext-culture-ao-ca', name: 'Ao cá phóng sinh', prompt: 'sacred release pond (Ao phóng sinh) in temple grounds for releasing captured fish and turtles as Buddhist merit practice', description: 'Ao trong sân chùa để phóng sinh cá, rùa theo tập tục Phật giáo.' },
        { id: 'ext-culture-nha-tho-ho', name: 'Nhà thờ Họ', prompt: 'ancestral clan temple with elaborate wooden architecture, altar rooms, and courtyard for family gatherings', description: 'Nhà thờ dòng họ với kiến trúc gỗ, phòng thờ, sân họp mặt.' },
        { id: 'ext-culture-dinh-lang', name: 'Đình làng', prompt: 'communal house (Đình) with large open hall, sweeping roof, dragon pillars, ceremonial space for village festivals', description: 'Đình làng với sảnh lớn, mái vút, cột rồng, không gian lễ hội.' },
        { id: 'ext-culture-chua-thien', name: 'Chùa Thiền', prompt: 'Zen Buddhist temple with simple architecture, meditation halls, monk quarters, and peaceful gardens', description: 'Chùa Thiền với kiến trúc giản dị, thiền đường, nhà sư, vườn yên tĩnh.' },
        { id: 'ext-culture-mieu-than', name: 'Miếu Thần địa phương', prompt: 'local deity shrine dedicated to guardian spirits, land gods, or legendary heroes of the village', description: 'Miếu thờ thần bảo vệ, thổ địa, anh hùng huyền thoại làng.' },
        { id: 'ext-culture-nha-to', name: 'Nhà Tổ nghề', prompt: 'guild house or craft ancestor temple honoring founders of traditional trades (pottery, carpentry, weaving)', description: 'Nhà thờ tổ nghề gốm, mộc, dệt... tôn vinh người sáng lập.' },
        { id: 'ext-culture-san-phoi', name: 'Sân phơi (lúa, cá, muối)', prompt: 'traditional drying yard for rice, fish, or salt, integrated into village landscape and economy', description: 'Sân phơi lúa, cá, muối - không gian kinh tế làng.' },
        { id: 'ext-culture-bai-tha-ma', name: 'Bãi Thả mả (vùng ven sông)', prompt: 'riverside ceremonial area for water blessing rituals and floating lanterns during festivals', description: 'Bãi ven sông làm lễ cầu phước, thả hoa đăng trong lễ hội.' },
        { id: 'ext-culture-cay-da-dinh', name: 'Cây Đa Đình làng', prompt: 'sacred banyan tree at communal house courtyard serving as village gathering point and symbol', description: 'Cây đa thiêng trong sân đình, điểm tụ họp và biểu tượng làng.' },
        { id: 'ext-culture-nui-than', name: 'Núi Thần/Rừng thiêng', prompt: 'sacred mountain or forest grove protected by village as spiritual and ecological heritage', description: 'Núi/rừng thiêng được làng bảo vệ, di sản tâm linh và sinh thái.' },
        { id: 'ext-culture-cho-que', name: 'Chợ quê truyền thống', prompt: 'traditional village market with thatched roof stalls, open-air trading, local produce display', description: 'Chợ làng với ki-ốt mái tranh, buôn bán ngoài trời, nông sản địa phương.' },
        { id: 'ext-culture-lau-nghe', name: 'Lầu Nghệ (biểu diễn dân gian)', prompt: 'traditional performance stage tower for folk music, Tuồng opera, and village celebrations', description: 'Lầu sân khấu biểu diễn hát tuồng, dân ca, lễ hội làng.' },
    ],
  },
];

export const EXTERIOR_ARCHITECTURAL_DETAILS = ARCHITECTURAL_ELEMENTS;